### ISSUE TITLE
Enhancement: solids.xml and detector.gdml are 28 times bigger than needed

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll-detector-generator#10]
There really is no single character difference between quartzSol_10001, quartzSol_10002, quartzSol_10003, etc. and similarly all the other rings. Is there a specific reason for storing these solids so many different times? Are we going to replace that with the actual as-built dimensions?

**Comment by wdconinc** [comment]
Same is true to some extent for detector.gdml. There is no need to duplicate logical volumes for the non-sensitive-detector volumes.

**Comment by cameronc137** [comment]
All components of the detector apparatus are intended to be made sensitive at some point or another so we can do exhaustive cross talk and sensitivity studies.

Also, the script for now doesn't make any assumptions about which detectors have different geometries. Hypothetically we could have all 28 slightly different (this hopefully won't happen, other than maybe in ring 5, but the goal was to write one thing that worked for ring 5 and extrapolate to the others).
